// ---- Shared constants (loaded first so everything can use them) ----
const BITE_TIME = 20;             // how long one bite animation lasts
const ATTACK_DMG = 5;            // damage a bite does to an enemy ant
const SPRINT_MULT = 1.7;         // speed multiplier while sprinting (Ctrl)
const STAMINA_MAX = 100;
const STAMINA_DRAIN = 0.9;       // stamina used per frame while sprinting
const STAMINA_REGEN = 0.4;       // stamina recovered per frame while resting
const EXHAUST_TIME = 300;        // frames (5s) you can't sprint after emptying stamina
const FOOD_PER_BEETLE = 3;       // (unused now — beetles drop meat instead)
const MEAT_VALUE = 6;            // food a delivered meat is worth
const START_FOOD = 24;           // each colony's starting food
const GROW_MAX = 100;            // larva growth needed to become an ant
const GROW_RATE = 1;             // extra growth per queen-fed frame
const PASSIVE_GROW = 0.1;        // slow growth all larvae get even unfed
const FEED_COST = 0.12;          // food used per grow tick
const LARVA_SPEED = 1.6;         // larva move speed (slower than an ant)
const FRIEND_COLOR = "#4fd04f";   // your side (green)
const FOE_COLOR = "#d0453f";      // enemies (red)
const WORLD = 2000;               // square world size
const VISION = 360;               // how far ants can see
const ROCK_STEP = 52;             // rock grid cell size
const ROCK_SIZE = 26;             // rock half-size (tiles touch edge to edge)
